FROM node:18-alpine

# Создаём пользователя
RUN adduser -D appuser

WORKDIR /app

# Копируем зависимости
COPY package.json ./
RUN npm install

# Копируем код
COPY middleware.js ./

# Меняем владельца
RUN chown -R appuser:appuser /app

# Переходим на non-root
USER appuser

EXPOSE 3000
CMD ["node", "middleware.js"]