FROM node:18-alpine

RUN mkdir -p /app/logs && chown -R node:node /app
RUN apk add --no-cache curl
WORKDIR /app
COPY middleware.js package.json ./
RUN npm install

USER node
EXPOSE 3000
CMD ["node", "middleware.js"]
